version: 1.0.1-{build}
before_build:
- ps: nuget restore
init:
- ps: Set-WinSystemLocale ru-RU
- ps: Start-Sleep -s 5
- ps: Restart-Computer
install:
- cmd: >-
    choco install onescript.cli -source https://www.myget.org/F/onescript -y

    refreshenv

    opm install opm

build:
  verbosity: minimal

after_build:
- cmd: >-
    copy onescript-extensions\onescript-extensions\bin\Debug\onescript-extensions.dll oslib\

    cd oslib

    opm build .

    cd ..

artifacts:
- path: oslib\*.ospx
  name: extensions
- path: oslib\*.dll
  name: components
